/*
 * 02 - Even Fibonacci numbers
 * ---------------------------
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */
package main

import "fmt"

func main() {

	var current int = 1
	var result int = 2
	var end = 4000000
	var temp int
	var array []int

	for result < end {
		temp = current + result
		current = result
		result = temp

		if (current % 2) == 0 {
			array = append(array, current)
		}
	}

	result = 0
	for _, v := range array {
		result += v
	}

	fmt.Println(result)
	fmt.Println(array)

}
